### ISSUE TITLE
[replace partition]: not listed as option when it should

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#30] opened 2016-06-22 19:15 UTC
![screenshot_20160622_190945](https://cloud.githubusercontent.com/assets/840070/16280122/6e1c420e-38be-11e6-9b3a-3badf0552631.png)

**Comment by star-buck** [comment] 2016-06-22 19:15
[calamares-20160622.txt](https://github.com/calamares/calamares-todos/files/328592/calamares-20160622.txt)

**Comment by teo** [comment] 2016-06-23 15:51
I've reproduced your partition table as described in the log you pasted, and I've tested both Calamares 2.2.3 and master (i.e. Calamares 2.3-beta2 with KPMcore 2.2, also thanks to Rohan for making new packages), all of this on the latest Netrunner Core live image. The issue is reproducible on Calamares 2.2.3.
I've ascertained that this is already fixed in the Calamares 2.3 series. I'll be releasing 2.3-RC1 shortly, and I advise the Netrunner team to package it and ship it. The switch from 2.2.x to 2.3 will require some unavoidable and possibly non-trivial configuration changes (because of new dependencies), so I'm available to assist.

**Closed** 2016-06-27 13:46 UTC
Labels: ready for QA
