### ISSUE TITLE
[missing alongside option]

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#27] opened 2016-05-14 17:21 UTC
a few versions earlier, calamares still showed alongside option with same setup, current cala 2.2.2 doesnt:
Previous:
![screenshot_20160130_144157](https://cloud.githubusercontent.com/assets/840070/15269747/b571b128-19f8-11e6-9ca7-dfe3b8a28d01.png)
2.2.2:
![screenshot_20160514_171451](https://cloud.githubusercontent.com/assets/840070/15269748/b7f835d4-19f8-11e6-9385-1011718a243d.png)
It even offered alongside with one more installed:
![screenshot_20160221_150246](https://cloud.githubusercontent.com/assets/840070/15269752/d37e54be-19f8-11e6-9c31-ec6902ddc7bf.png)

**Comment by star-buck** [comment] 2016-05-14 17:25
a few versions earlier, calamares still showed alongside option with same setup, current cala 2.2.2 doesnt:
Previous:
![screenshot_20160130_144157](https://cloud.githubusercontent.com/assets/840070/15269747/b571b128-19f8-11e6-9ca7-dfe3b8a28d01.png)
2.2.2:
![screenshot_20160514_171451](https://cloud.githubusercontent.com/assets/840070/15269748/b7f835d4-19f8-11e6-9385-1011718a243d.png)
It even offered alongside with one more installed:
![screenshot_20160221_150246](https://cloud.githubusercontent.com/assets/840070/15269752/d37e54be-19f8-11e6-9c31-ec6902ddc7bf.png)

**Comment by teo** [comment] 2016-05-16 17:57
I've tried to reproduce this for a while today on the test box but I've had no success so far.
Are all of those partitions primary or are some of them logical inside an extended partition? Netrunner Debian has Calamares configured to not show nested partitions so I can't tell from the 2.2.2 screenshot.
Could you please paste the output of `lsblk` for me? The output might help me a lot in reproducing and fixing this.

**Comment by teo** [comment] 2016-05-17 10:01
It turns out that this is a deployment issue, caused by a broken e2fsprogs, specifically the `dumpe2fs` tool, which segfaults. Because of this, we cannot check for used space on an ext2/3/4 partition, and resize operations are automatically reported as disabled by KPMcore.
KPMcore requires e2fsprogs 1.42.13, which has been out for a year now. Because of what I assume to be common Debian packaging policy, Debian still ships the very old and broken e2fsprogs 1.42.12 even though a fix has been out for a very long time. I had even published a [packaging advisory](https://calamares.io/Important-e2fsprogs-issue-discovered/) last year, warning packagers to ship 1.42.13 and **never 1.42.12**.
No other distro I've tried ships such an old e2fsprogs today.
I advise that Netrunner Debian (or any other distro, for that matter) immediately switch to e2fsprogs 1.42.13: once the new e2fsprogs lands on the Netrunner Debian Complete live image, this issue should be resolved.

**Closed** 2016-06-27 13:46 UTC
Labels: bug, ready for QA
